php:
  preset: laravel
  disabled:
<<<<<<< HEAD
    - no_unused_imports
=======
    - unused_use
>>>>>>> origin/master
  finder:
    not-name:
      - index.php
      - server.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
